package net.runelite.client.plugins.pluginhub.net.runelite.api;

/**
 * An enumeration of PK skulls.
 */
public enum SkullIcon
{
	/**
	 * White skull from PVP world or wilderness
	 */
	SKULL,
	/**
	 * Red skull from Tzhaar Fight Pits
	 */
	SKULL_FIGHT_PIT,
	/**
	 * Deadman mode sprite carrying one key
	 */
	DEAD_MAN_ONE,
	/**
	 * Deadman mode sprite carrying two keys
	 */
	DEAD_MAN_TWO,
	/**
	 * Deadman mode sprite carrying three keys
	 */
	DEAD_MAN_THREE,
	/**
	 * Deadman mode sprite carrying four keys
	 */
	DEAD_MAN_FOUR,
	/**
	 * Deadman mode sprite carrying five keys
	 */
	DEAD_MAN_FIVE,
}

/* This file is automatically generated. Do not edit. */