package net.runelite.client.plugins.pluginhub.com.ameliaxt;

import net.runelite.api.gameval.InterfaceID.MagicSpellbook;

import java.util.Map;

public class TargetableSpells {
    public static final Map<Integer, String> TARGETABLE_SPELL_MAP = Map.ofEntries(
        Map.entry(MagicSpellbook.BIND, "bind"),
        Map.entry(MagicSpellbook.BLOOD_BARRAGE, "blood barrage"),
        Map.entry(MagicSpellbook.BLOOD_BLITZ, "blood blitz"),
        Map.entry(MagicSpellbook.BLOOD_BURST, "blood burst"),
        Map.entry(MagicSpellbook.BLOOD_RUSH, "blood rush"),
        Map.entry(MagicSpellbook.CHARGE_AIR_ORB, "charge air orb"),
        Map.entry(MagicSpellbook.CHARGE_EARTH_ORB, "charge earth orb"),
        Map.entry(MagicSpellbook.CHARGE_FIRE_ORB, "charge fire orb"),
        Map.entry(MagicSpellbook.CHARGE_WATER_ORB, "charge water orb"),
        Map.entry(MagicSpellbook.CLAWS_OF_GUTHIX, "claws of guthix"),
        Map.entry(MagicSpellbook.CONFUSE, "confuse"),
        Map.entry(MagicSpellbook.CRUMBLE_UNDEAD, "crumble undead"),
        Map.entry(MagicSpellbook.CURE_OTHER, "cure other"),
        Map.entry(MagicSpellbook.CURE_PLANT, "cure plant"),
        Map.entry(MagicSpellbook.CURSE, "curse"),
        Map.entry(MagicSpellbook.DARK_DEMONBANE, "dark demonbane"),
        Map.entry(MagicSpellbook.DARK_LURE, "dark lure"),
        Map.entry(MagicSpellbook.EARTH_BLAST, "earth blast"),
        Map.entry(MagicSpellbook.EARTH_BOLT, "earth bolt"),
        Map.entry(MagicSpellbook.EARTH_STRIKE, "earth strike"),
        Map.entry(MagicSpellbook.EARTH_SURGE, "earth surge"),
        Map.entry(MagicSpellbook.EARTH_WAVE, "earth wave"),
        Map.entry(MagicSpellbook.ENCHANT_1, "lvl-1 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_2, "lvl-2 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_3, "lvl-3 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_4, "lvl-4 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_5, "lvl-5 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_6, "lvl-6 enchant"),
        Map.entry(MagicSpellbook.ENCHANT_7, "lvl-7 enchant"),
        Map.entry(MagicSpellbook.ENERGY_TRANS, "energy transfer"),
        Map.entry(MagicSpellbook.ENFEEBLE, "enfeeble"),
        Map.entry(MagicSpellbook.ENTANGLE, "entangle"),
        Map.entry(MagicSpellbook.FERTILE_SOIL, "fertile soil"),
        Map.entry(MagicSpellbook.FIRE_BLAST, "fire blast"),
        Map.entry(MagicSpellbook.FIRE_BOLT, "fire bolt"),
        Map.entry(MagicSpellbook.FIRE_STRIKE, "fire strike"),
        Map.entry(MagicSpellbook.FIRE_SURGE, "fire surge"),
        Map.entry(MagicSpellbook.FIRE_WAVE, "fire wave"),
        Map.entry(MagicSpellbook.FLAMES_OF_ZAMORAK, "flame of zamorak"),
        Map.entry(MagicSpellbook.GHOSTLY_GRASP, "ghostly grasp"),
        Map.entry(MagicSpellbook.HEAL_OTHER, "heal other"),
        Map.entry(MagicSpellbook.HIGH_ALCHEMY, "high alchemy"),
        Map.entry(MagicSpellbook.IBAN_BLAST, "iban blast"),
        Map.entry(MagicSpellbook.ICE_BARRAGE, "ice barrage"),
        Map.entry(MagicSpellbook.ICE_BLITZ, "ice blitz"),
        Map.entry(MagicSpellbook.ICE_BURST, "ice burst"),
        Map.entry(MagicSpellbook.ICE_RUSH, "ice rush"),
        Map.entry(MagicSpellbook.INFERIOR_DEMONBANE, "inferior demonbane"),
        Map.entry(MagicSpellbook.LOW_ALCHEMY, "low alchemy"),
        Map.entry(MagicSpellbook.MAGIC_DART, "magic dart"),
        Map.entry(MagicSpellbook.MONSTER_EXAMINE, "monster examine"),
        Map.entry(MagicSpellbook.REANIMATION_ADEPT, "adept reanimation"),
        Map.entry(MagicSpellbook.REANIMATION_BASIC, "basic reanimation"),
        Map.entry(MagicSpellbook.REANIMATION_EXPERT, "expert reanimation"),
        Map.entry(MagicSpellbook.REANIMATION_MASTER, "master reanimation"),
        Map.entry(MagicSpellbook.RECHARGE_DRAGONSTONE, "recharge dragonstone"),
        Map.entry(MagicSpellbook.RESURRECT_CROPS, "resurrect crops"),
        Map.entry(MagicSpellbook.SARADOMIN_STRIKE, "saradomin strike"),
        Map.entry(MagicSpellbook.SHADOW_BARRAGE, "shadow barrage"),
        Map.entry(MagicSpellbook.SHADOW_BLITZ, "shadow blitz"),
        Map.entry(MagicSpellbook.SHADOW_BURST, "shadow burst"),
        Map.entry(MagicSpellbook.SHADOW_RUSH, "shadow rush"),
        Map.entry(MagicSpellbook.SKELETAL_GRASP, "skeletal grasp"),
        Map.entry(MagicSpellbook.SMOKE_BARRAGE, "smoke barrage"),
        Map.entry(MagicSpellbook.SMOKE_BLITZ, "smoke blitz"),
        Map.entry(MagicSpellbook.SMOKE_BURST, "smoke burst"),
        Map.entry(MagicSpellbook.SMOKE_RUSH, "smoke rush"),
        Map.entry(MagicSpellbook.SNARE, "snare"),
        Map.entry(MagicSpellbook.STAT_SPY, "stat spy"),
        Map.entry(MagicSpellbook.STUN, "stun"),
        Map.entry(MagicSpellbook.SUPERHEAT, "superheat item"),
        Map.entry(MagicSpellbook.SUPERIOR_DEMONBANE, "superior demonbane"),
        Map.entry(MagicSpellbook.TELEGRAB, "telekinetic grab"),
        Map.entry(MagicSpellbook.TELEOTHER_CAMELOT, "teleother camelot"),
        Map.entry(MagicSpellbook.TELEOTHER_FALADOR, "teleother falador"),
        Map.entry(MagicSpellbook.TELEOTHER_LUMBRIDGE, "teleother lumbridge"),
        Map.entry(MagicSpellbook.UNDEAD_GRASP, "undead grasp"),
        Map.entry(MagicSpellbook.VENGEANCE_OTHER, "vengeance other"),
        Map.entry(MagicSpellbook.VULNERABILITY, "vulnerability"),
        Map.entry(MagicSpellbook.WATER_BLAST, "water blast"),
        Map.entry(MagicSpellbook.WATER_BOLT, "water bolt"),
        Map.entry(MagicSpellbook.WATER_STRIKE, "water strike"),
        Map.entry(MagicSpellbook.WATER_SURGE, "water surge"),
        Map.entry(MagicSpellbook.WATER_WAVE, "water wave"),
        Map.entry(MagicSpellbook.WEAKEN, "weaken"),
        Map.entry(MagicSpellbook.WIND_BLAST, "wind blast"),
        Map.entry(MagicSpellbook.WIND_BOLT, "wind bolt"),
        Map.entry(MagicSpellbook.WIND_STRIKE, "wind strike"),
        Map.entry(MagicSpellbook.WIND_SURGE, "wind surge"),
        Map.entry(MagicSpellbook.WIND_WAVE, "wind wave"),
        Map.entry(MagicSpellbook.XBOWS_ENCHANT, "enchant crossbow bolt"
    ));
}
